### ISSUE TITLE
Wolfenstein goes past splash screen and shows a black screen

### ISSUE THREAD

**Issue by MegaTKC** [os-js/osjs-wolfenstein3d-application#2]
I just installed Wolfenstein on my OS.js application and I don't know what happens. The game just goes to the splash screen and shows a black screen. In the console, the resources or assets to Wolfenstein are showing and they look like they are running.

**Comment by andersevenrud** [comment]
You installed this from npm ?

**Comment by MegaTKC** [comment]
> You installed this from npm ?

Yes, I did install it from npm. I ran both commands, as well as `npm audit fix`

EDIT: I installed my OS.js web app on a repl.it project.

**Comment by andersevenrud** [comment]
Hm. I just set up a clean install to test this myself, and I was unable to reproduce. It's getting fairly late here, so I can't look at this now, but I will dig into this further ASAP.

What browser are you on btw ? Also try running incognito mode or something (with extensions disabled).

**Comment by MegaTKC** [comment]
I am using Chrome. On Chrome OS. I tried incognito mode with no extensions, but it still doesn't work.

**Comment by MegaTKC** [comment]
![Screenshot 2021-10-27 3 08 46 PM](https://user-images.githubusercontent.com/59368582/139154601-53af4756-275d-4e4b-b197-c3c68c357bb2.png)

I just pulled up inspect element when running the game. I got this in the console.

**Comment by MegaTKC** [comment]
I've tried hosting OS.js on another service, ide.goorm.io works with OS.js. Wolfenstein works on there.

**Comment by andersevenrud** [comment]
Okay, great! Then I'll close this as there's nothing I can do about it.
